//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public enum AlertType : int
    {
        GPSAlert = 0,
        CategoryAlert = 1,
        NotUsedAlert = 2,
        Literal = 3
    }
}
