//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C_ModelContainer : DbContext
    {
        public C_ModelContainer()
            : base("name=C_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<CouponAlert> CouponAlerts { get; set; }
        public virtual DbSet<CouponOrder> CouponOrders { get; set; }
        public virtual DbSet<SocialNetworkProfile> SocialNetworkProfiles1 { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
    }
}
