//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public enum CategoryTypes : int
    {
        Resturant = 0,
        Liesure = 1,
        Consumer = 2,
        Sports = 3,
        LifeStyle = 4
    }
}
