//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costumer : User
    {
        public Costumer()
        {
            this.SocialCoupons = new HashSet<SocialCoupon>();
            this.CouponOrders = new HashSet<CouponOrder>();
            this.CouponAlerts = new HashSet<CouponAlert>();
            this.SocialNetworkProfiles = new HashSet<SocialNetworkProfile>();
            this.Categories = new HashSet<Categories>();
        }
    
        public double age { get; set; }
        public Gender gender { get; set; }
    
        public virtual ICollection<SocialCoupon> SocialCoupons { get; set; }
        public virtual ICollection<CouponOrder> CouponOrders { get; set; }
        public virtual ICollection<CouponAlert> CouponAlerts { get; set; }
        public virtual ICollection<SocialNetworkProfile> SocialNetworkProfiles { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
