//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.CouponAlerts = new HashSet<CouponAlert>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double originalPrice { get; set; }
        public double discountPrice { get; set; }
        public double aggregatedRank { get; set; }
        public System.DateTime lastDateForUse { get; set; }
        public int reaminingQuantity { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<CouponAlert> CouponAlerts { get; set; }
        public virtual CouponOrder CouponOrder { get; set; }
        public virtual Categories Category { get; set; }
    }
}
