//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponAlert
    {
        public CouponAlert()
        {
            this.Costumer = new HashSet<Costumer>();
        }
    
        public int Id { get; set; }
        public AlertType alerType { get; set; }
        public string text { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual ICollection<Costumer> Costumer { get; set; }
    }
}
