//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmOwner : User
    {
        public FirmOwner()
        {
            this.Firms = new HashSet<Firm>();
        }
    
    
        public virtual SystemAdmin SystemAdmin { get; set; }
        public virtual ICollection<Firm> Firms { get; set; }
    }
}
